//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAMBAR_TEMPAT_WISATA
    {
        public int ID_GAMBAR_WISATA { get; set; }
        public int ID_WISATA { get; set; }
        public string NAMA_GAMBAR_WISATA { get; set; }
        public string KETERANGAN_GAMBAR_WISATA { get; set; }
        public string GAMBAR_WISATA { get; set; }
    }
}
