//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOTEL
    {
        public int ID_HOTEL { get; set; }
        public string NAMA_HOTEL { get; set; }
        public string ALAMAT_HOTEL { get; set; }
        public string TELEPON_HOTEL { get; set; }
        public Nullable<double> BINTANG { get; set; }
        public string WEBSITE { get; set; }
        public string LATITUDE_HOTEL { get; set; }
        public string LONGITUDE_HOTE { get; set; }
    }
}
