//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KATEGORI_RUMAH_MAKAN
    {
        public int ID_KATEGORI_RUMAH_MAKAN { get; set; }
        public string KATEGORI_RUMAH_MAKAN1 { get; set; }
        public string DESKRIPSI_KATEGORI_RUMAH_MAKAN { get; set; }
    }
}
