//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KATEGORI_TRANSPORTASI
    {
        public int ID_KATEGORI_TRANSPORTASI { get; set; }
        public string NAMA_KATEGORI_TRANSPORTASI { get; set; }
        public string DESKRIPSI_KATEGORI_TRANSPORTASI { get; set; }
    }
}
