//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAKANAN
    {
        public int ID_MAKANAN { get; set; }
        public string NAMA_MAKANAN { get; set; }
        public Nullable<decimal> HARGA_NORMAL_MAKANAN { get; set; }
    }
}
