//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MINUMAN
    {
        public int ID_MINUMAN { get; set; }
        public string MINUMAN1 { get; set; }
        public Nullable<decimal> HARGA_NORMAL_MINUMAN { get; set; }
    }
}
