//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONTH_EVENT
    {
        public int ID_MONTH_EVENT { get; set; }
        public string NAMA_EVENT { get; set; }
        public string TELEPON_EVENT { get; set; }
        public Nullable<System.DateTime> TANGGAL_MULAI { get; set; }
        public Nullable<System.DateTime> TANGGAL_BERAKHIR { get; set; }
        public string LOKASI_EVENT { get; set; }
        public string LATITUDE_EVENT { get; set; }
        public string LONGITUDE_EVENT { get; set; }
        public string DESKRIPSI_EVENT { get; set; }
    }
}
