//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUMAH_MAKAN
    {
        public int ID_RUMAH_MAKAN { get; set; }
        public int ID_KATEGORI_RUMAH_MAKAN { get; set; }
        public string NAMA_RUMAH_MAKAN { get; set; }
        public string ALAMAT_RUMAH_MAKAN { get; set; }
        public string TELEPON_RUMAH_MAKAN { get; set; }
        public string LATITUDE_RUMAH_MAKAN { get; set; }
        public string LONGITUDE_RUMAH_MAKAN { get; set; }
        public string DESKRIPSI_RUMAH_MAKAN { get; set; }
        public Nullable<decimal> HARGA_PENAMBAH { get; set; }
    }
}
