//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOP_WISATA
    {
        public int ID_TOP_WISATA { get; set; }
        public Nullable<int> ID_WISATA { get; set; }
        public Nullable<double> RATE_TOP_WISATA { get; set; }
    }
}
