//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTASI
    {
        public int ID_TRANSPORTASI { get; set; }
        public int ID_KATEGORI_TRANSPORTASI { get; set; }
        public string NAMA_PERUSAHAAN_TRANSPORTASI { get; set; }
        public string NOMOR_TELEPON_TRANSPORTASI { get; set; }
        public string RUTE_ASAL { get; set; }
        public string RUTE_TUJUAN { get; set; }
        public string RUTE { get; set; }
        public Nullable<System.TimeSpan> JAM_OPERASIONAL { get; set; }
        public Nullable<decimal> TARIF_MINIMAL { get; set; }
    }
}
