//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WISATA
    {
        public int ID_WISATA { get; set; }
        public Nullable<int> ID_TOP_WISATA { get; set; }
        public int ID_KATEGORI_WISATA { get; set; }
        public string NAMA_WISATA { get; set; }
        public string LOKASI_WISATA { get; set; }
        public string TELEPON_WISATA { get; set; }
        public string DESKRIPSI_WISATA { get; set; }
        public string LATITUDE_WISATA { get; set; }
        public string LONGITUDE_WISATA { get; set; }
    }
}
